const INDICATORS = {
    "NY.GDP.PCAP.KD": "GDP per capita (USD)",
    "SI.POV.GINI": "Estimated Gini index",
    "EG.USE.PCAP.KG.OE": "Energy use per capita (kg of oil equivalent)",
    "SL.UEM.TOTL.FE.NE.ZS": "Female unemployment rate (%)",
    "SL.UEM.TOTL.MA.NE.ZS": "Male unemployment rate (%)",
    "per_si_allsi.adq_pop_tot": "Adequacy of social insurance programs (%)",
    "per_allsp.adq_pop_tot": "Adequacy of social protection and labor programs (%)",
    "per_sa_allsa.adq_pop_tot": "Adequacy of social safety net programs (%)",
    "per_lm_alllm.adq_pop_tot": "Adequacy of unemployment benefits and ALMP (%)",
    "GC.XPN.TRFT.ZS": "Subsidies and other transfers (% of expense)",
    "SH.STA.SUIC.P5": "Suicide mortality rate (per 100,000 people)",
    "SH.STA.SUIC.FE.P5": "Suicide mortality rate (per 100,000 women)",
    "SH.STA.SUIC.MA.P5": "Suicide mortality rate (per 100,000 men)",
    "IC.LGL.CRED.XQ": "Strength of legal rights index (0=weak to 12=strong)",
    "SP.DYN.LE00.IN": "Overall life expectancy at birth (years)",
    "SP.DYN.LE00.FE.IN": "Female life expectancy at birth (years)",
    "SP.DYN.LE00.MA.IN": "Male life expectancy at birth (years)",
    "SL.UEM.TOTL.NE.ZS": "Total Unemployment rate (%)",
    "SH.STA.AIRP.P5": "Household and ambient air pollution mortality rate (per 100,000 people)",
    "SH.STA.POIS.P5": "Unintentional poisoning mortality rate (per 100,000 people)",
    "SH.XPD.CHEX.PC.CD": "Health expenditure per capita (USD)",
    "hf_score": "Human Freedom Index",
    "pf_rol": "Score on rule of law",
    "pf_ss": "Score on security and safety",
    "pf_movement": "Score on freedom of movement",
    "pf_religion": "Score on freedom of religion",
    "pf_association": "Score on freedom of association",
    "pf_expression": "Score on freedom of speech",
    "pf_identity": "Score on freedom of identity",
    "pf_score": "Score on personal freedom",
    "ef_government": "Score on government size",
    "ef_legal": "Score on legal system",
    "ef_money": "Score on monetary system",
    "ef_trade": "Score on freedom of internation trade",
    "ef_regulation": "Score on regulations",
    "ef_score": "Score economic freedom",
    "Corruption Perceptions Index": "Corruption Perceptions Index",
    "IQ.CPA.TRAN.XQ": "Transparency, accountability, and corruption rating (1=low to 6=high)",
    "World Giving Index": "World Giving Index (%)",
    "helping": "Helping rate (%)",
    "donating": "Donating rate (%)",
    "volunteer": "Volunteering rate (%)"    
}
